@AccountingServer_HostAddress = https://localhost:7098

GET {{AccountingServer_HostAddress}}/api/PurchInvAndExpenses

###

@DateFrom=2024-12-01
@DateTo=2024-12-30
GET {{AccountingServer_HostAddress}}/api/PurchInvAndExpenses/betweenDates?DateFrom={{DateFrom}}&DateTo={{DateTo}}

###

@invNo=PI00000930
GET {{AccountingServer_HostAddress}}/api/PurchInvAndExpenses/{{invNo}}

###

GET {{AccountingServer_HostAddress}}/

###

GET {{AccountingServer_HostAddress}}/api/Vendors

###

GET {{AccountingServer_HostAddress}}/api/PurchInvAndExpenses

###

GET {{AccountingServer_HostAddress}}/api/BankAccountLedgerItems/?toDate=2025-03-02&accountId=12345

###
@FromDate=2024-12-01
@ToDate=2025-12-30
@Company=JMJ
GET {{AccountingServer_HostAddress}}/api/CustomerInvoices?FromDate={{FromDate}}&ToDate={{ToDate}}&Company={{Company}}

###
@FromDate=2024-12-01
@ToDate=2025-12-30
@Company=CDF
GET {{AccountingServer_HostAddress}}/api/VendorInvoices?FromDate={{FromDate}}&ToDate={{ToDate}}&Company={{Company}}

###
@Company=CDF
GET {{AccountingServer_HostAddress}}/api/LateCustomerInvoices?Company={{Company}}

###
